<a href="https://colab.research.google.com/github/RobbieCV/BdeB-IA/blob/main/Pratique_Roberto_Castro_Vexler_2020_10_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pratique
#Roberto Castro Vexler
#2020-10-22


In [ ]:
## -- Numpy et Pandas ( october 20/10/2020)

In [ ]:
## --- pratique 1:
## construire un vecteur avec [3,4,5,6]
## assigner resultat a la variable vector
## indice : np.array([3,4,5,6])
import numpy as np

vector =np.array([3,4,5,9])

print(vector)

[3 4 5 6]


In [ ]:
## --- pratique 2:
## construire une matrice  depuis la liste de listes [[2,5,15],[20,50,50],[34,99,45]]
## Afficher les resultats
## assigner le resultat a la variable matrix 
matrice = np.array([[2,5,15],[20,50,50],[34,99,45]])
matrice

array([[ 2,  5, 15],
       [20, 50, 50],
       [34, 99, 45]])

In [ ]:
## --- pratique 3:
## Donner la taille du tableau [1,2,3,4]suivant puis changer sa taille
## Afficher les resultats
## indication : shape, reshape
tab = np.array([1,2,3,4])
print(tab.shape)
#reshape
tab.reshape(2,2)

(4,)


array([[1, 2],
       [3, 4]])

In [ ]:
## --- pratique 4:
## Donner la taille de la matrice [[5,10,15], [20,25,30], [40,45,50]] suivant puis changer sa taille 
## Afficher les resultats
## indication : shape, reshape
matrice = np.array([[5,10,15], [20,25,30], [40,45,50]])
print(matrice.shape)
#reshape
matrice.reshape(1,9)

(3, 3)


array([[ 5, 10, 15, 20, 25, 30, 40, 45, 50]])

In [ ]:
## --- pratique 5:
## Executer le code suivant ( en specifiant le path du fichier)
import numpy as np
fichier = np.genfromtxt("data_numpy.csv", delimiter=",")
## Utiliser les fonctions type() et print() pour afficher le type de fichier 
print(type(fichier))
#show fichier results
print(fichier)

<class 'numpy.ndarray'>
[[      nan       nan       nan       nan]
 [1.986e+03       nan       nan 0.000e+00]
 [1.986e+03       nan       nan 5.000e-01]
 ...
 [1.986e+03       nan       nan 2.540e+00]
 [1.987e+03       nan       nan 0.000e+00]
 [1.986e+03       nan       nan 5.150e+00]]


In [ ]:
## --- pratique 6:
## creer un vecteur random ayant 4 valeurs
## creer une matrice random de taille (2X2)
np.random.seed(100)
arr = np.random.randint(0,100,4)
arr.reshape(2,2)


array([[ 8, 24],
       [67, 87]])

In [ ]:
## --- pratique 7:
# creer un vecteur depuis la liste[1, 2, 3, 4] et afficher son type
##solution
import numpy as np
numbers=np.array([1, 2, 3, 4])
print(numbers)
print(numbers.dtype)

[1 2 3 4]
int32


In [ ]:
## --- pratique 8
## Afficher toutes les lignes des 2 premières colonnes de data_numpy à la variable first_two_columns.
# Afficher les 10 premières lignes de la première colonne de data_numpy à la variable first_ten_years.
# Afficher les 10 premières lignes de toutes les colonnes de data_numpy à la variable first_ten_rows.
# Afficher les 20 premières lignes des colonnes d'indice 1 et 2 de data_numpy à la variable first_twenty_regions.
display(fichier)
first_two_columns = fichier[:,0:2]
display(first_two_columns)
first_ten_rows = fichier[0:10,0]
display(first_ten_rows)
first_ten_rows = fichier[0:10,:]
display(first_ten_rows)
first_twenty_regions = fichier[0:20,1:2]
display(first_twenty_regions)

array([[      nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan, 5.000e-01],
       ...,
       [1.986e+03,       nan,       nan, 2.540e+00],
       [1.987e+03,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan, 5.150e+00]])

array([[  nan,   nan],
       [1986.,   nan],
       [1986.,   nan],
       ...,
       [1986.,   nan],
       [1987.,   nan],
       [1986.,   nan]])

array([  nan, 1986., 1986., 1985., 1986., 1987., 1987., 1987., 1985.,
       1986.])

array([[      nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan, 5.000e-01],
       [1.985e+03,       nan,       nan, 1.620e+00],
       [1.986e+03,       nan,       nan, 4.270e+00],
       [1.987e+03,       nan,       nan, 1.980e+00],
       [1.987e+03,       nan,       nan, 0.000e+00],
       [1.987e+03,       nan,       nan, 1.300e-01],
       [1.985e+03,       nan,       nan, 3.900e-01],
       [1.986e+03,       nan,       nan, 1.550e+00]])

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

In [ ]:
## --- pratique 9
#Importer la librairie pandas.
#Utiliser la fonction pandas.read_csv() pour lire le fichier "food_info.csv" 
#Utiliser les fonctions type() et print() pour afficher le type de food_info

import pandas as pd
df = pd.read_csv("food_info.csv")
display(df)

NDB_No                                          Shrt_Desc  Water_(g)  \
0       1001                                   BUTTER WITH SALT      15.87   
1       1002                           BUTTER WHIPPED WITH SALT      15.87   
2       1003                               BUTTER OIL ANHYDROUS       0.24   
3       1004                                        CHEESE BLUE      42.41   
4       1005                                       CHEESE BRICK      41.11   
5       1006                                        CHEESE BRIE      48.42   
6       1007                                   CHEESE CAMEMBERT      51.80   
7       1008                                     CHEESE CARAWAY      39.28   
8       1009                                     CHEESE CHEDDAR      37.10   
9       1010                                    CHEESE CHESHIRE      37.65   
10      1011                                       CHEESE COLBY      38.20   
11      1012                CHEESE COTTAGE CRMD LRG OR SML CURD      79.79   
12      1013                        CHEESE COTTAGE CRMD W/FRUIT      79.64   
13      1014   CHEESE COTTAGE NONFAT UNCRMD DRY LRG OR SML CURD      81.01   
14      1015                   CHEESE COTTAGE LOWFAT 2% MILKFAT      81.24   
15      1016                   CHEESE COTTAGE LOWFAT 1% MILKFAT      82.48   
16      1017                                       CHEESE CREAM      54.44   
17      1018                                        CHEESE EDAM      41.56   
18      1019                                        CHEESE FETA      55.22   
19      1020                                     CHEESE FONTINA      37.92   
20      1021                                     CHEESE GJETOST      13.44   
21      1022                                       CHEESE GOUDA      41.46   
22      1023                                     CHEESE GRUYERE      33.19   
23      1024                                   CHEESE LIMBURGER      48.42   
24      1025                                    CHEESE MONTEREY      41.01   
25      1026                         CHEESE MOZZARELLA WHL MILK      50.01   
26      1027                CHEESE MOZZARELLA WHL MILK LO MOIST      48.38   
27      1028                   CHEESE MOZZARELLA PART SKIM MILK      53.78   
28      1029               CHEESE MOZZARELLA LO MOIST PART-SKIM      45.54   
29      1030                                    CHEESE MUENSTER      41.77   
...      ...                                                ...        ...   
8588   43544         BABYFOOD CRL RICE W/ PEARS & APPL DRY INST       2.00   
8589   43546                     BABYFOOD BANANA NO TAPIOCA STR      76.70   
8590   43550                     BABYFOOD BANANA APPL DSSRT STR      83.10   
8591   43566       SNACKS TORTILLA CHIPS LT (BAKED W/ LESS OIL)       1.30   
8592   43570  CEREALS RTE POST HONEY BUNCHES OF OATS HONEY RSTD       5.00   
8593   43572                         POPCORN MICROWAVE LOFAT&NA       2.80   
8594   43585                       BABYFOOD FRUIT SUPREME DSSRT      81.60   
8595   43589                               CHEESE SWISS LOW FAT      59.60   
8596   43595             BREAKFAST BAR CORN FLAKE CRUST W/FRUIT      14.50   
8597   43597                            CHEESE MOZZARELLA LO NA      49.90   
8598   43598                           MAYONNAISE DRSNG NO CHOL      21.70   
8599   44005                          OIL CORN PEANUT AND OLIVE       0.00   
8600   44018                   SWEETENERS TABLETOP FRUCTOSE LIQ      23.90   
8601   44048                              CHEESE FOOD IMITATION      55.50   
8602   44055                                CELERY FLAKES DRIED       9.00   
8603   44061           PUDDINGS CHOC FLAVOR LO CAL INST DRY MIX       4.20   
8604   44074                    BABYFOOD GRAPE JUC NO SUGAR CND      84.40   
8605   44110                   JELLIES RED SUGAR HOME PRESERVED      53.00   
8606   44158                         PIE FILLINGS BLUEBERRY CND      54.66   
8607   44203               C

In [ ]:
##--- pratique 10
#Afficher la 1000e ligne du dataframe food_info 
#solution
display(df.loc[999])

NDB_No                                           5236
Shrt_Desc          TURKEY YOUNG HEN SKN ONLY CKD RSTD
Water_(g)                                       35.53
Energ_Kcal                                        482
Protein_(g)                                     19.03
Lipid_Tot_(g)                                   44.45
Ash_(g)                                          0.63
Carbohydrt_(g)                                      0
Fiber_TD_(g)                                        0
Sugar_Tot_(g)                                     NaN
Calcium_(mg)                                       32
Iron_(mg)                                        1.82
Magnesium_(mg)                                     15
Phosphorus_(mg)                                   133
Potassium_(mg)                                    155
Sodium_(mg)                                        44
Zinc_(mg)                                        2.06
Copper_(mg)                                     0.078
Manganese_(mg)              

In [ ]:
##--- pratique 11
#Assigner la colonne "protein_(g)" à la variable protein.
#Assigner la colonne "Cholestrl_(mg)" à la variable cholesterol.
#Afficher les résultats.
#describe(df)
protein = df["Protein_(g)"]
display(protein)
cholesterol = df["Cholestrl_(mg)"]
display(cholesterol)

0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
5       20.75
6       19.80
7       25.18
8       24.04
9       23.37
10      23.76
11      11.12
12      10.69
13      10.34
14      10.45
15      12.39
16       5.93
17      24.99
18      14.21
19      25.60
20       9.65
21      24.94
22      29.81
23      20.05
24      24.48
25      22.17
26      21.60
27      24.26
28      24.58
29      23.41
        ...  
8588     6.60
8589     1.00
8590     0.30
8591     8.70
8592     7.12
8593    12.60
8594     0.50
8595    28.40
8596     4.40
8597    27.50
8598     0.00
8599     0.00
8600     0.00
8601     4.08
8602    11.30
8603     5.30
8604     0.00
8605     0.30
8606     0.41
8607     0.08
8608    10.08
8609     1.60
8610     0.81
8611    75.16
8612    16.40
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64

0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
5       100.0
6        72.0
7        93.0
8       102.0
9       103.0
10       95.0
11       17.0
12       13.0
13        7.0
14       12.0
15        4.0
16      110.0
17       89.0
18       89.0
19      116.0
20       94.0
21      114.0
22      110.0
23       90.0
24       89.0
25       79.0
26       89.0
27       64.0
28       65.0
29       96.0
        ...  
8588      0.0
8589      0.0
8590      0.0
8591      0.0
8592      0.0
8593      0.0
8594      0.0
8595     35.0
8596      0.0
8597     54.0
8598      0.0
8599      0.0
8600      0.0
8601      6.0
8602      0.0
8603      0.0
8604      0.0
8605      0.0
8606      0.0
8607      0.0
8608      0.0
8609      0.0
8610      0.0
8611      0.0
8612     50.0
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), Length: 8618, dtype: float64

In [ ]:

##--- pratique 12
#Sélectionner les colonnes 'Shrt__Desc', 'Selenium_(mcg)' et 'Thiamin_(mg)' 
#et assigner le dataframe résultant à la variable selenium_thiamin.
#Afficher le résultat.
#describe(df)

selenium_thiamin = df[['Shrt_Desc','Selenium_(mcg)', 'Thiamin_(mg)']]
display(selenium_thiamin)

Shrt_Desc  Selenium_(mcg)  \
0                                      BUTTER WITH SALT             1.0   
1                              BUTTER WHIPPED WITH SALT             1.0   
2                                  BUTTER OIL ANHYDROUS             0.0   
3                                           CHEESE BLUE            14.5   
4                                          CHEESE BRICK            14.5   
5                                           CHEESE BRIE            14.5   
6                                      CHEESE CAMEMBERT            14.5   
7                                        CHEESE CARAWAY            14.5   
8                                        CHEESE CHEDDAR            28.3   
9                                       CHEESE CHESHIRE            14.5   
10                                         CHEESE COLBY            14.5   
11                  CHEESE COTTAGE CRMD LRG OR SML CURD             9.7   
12                          CHEESE COTTAGE CRMD W/FRUIT             7.7   
13     CHEESE COTTAGE NONFAT UNCRMD DRY LRG OR SML CURD             9.4   
14                     CHEESE COTTAGE LOWFAT 2% MILKFAT            11.9   
15                     CHEESE COTTAGE LOWFAT 1% MILKFAT             9.0   
16                                         CHEESE CREAM             2.4   
17                                          CHEESE EDAM            14.5   
18                                          CHEESE FETA            15.0   
19                                       CHEESE FONTINA            14.5   
20                                       CHEESE GJETOST            14.5   
21                                         CHEESE GOUDA            14.5   
22                                       CHEESE GRUYERE            14.5   
23                                     CHEESE LIMBURGER            14.5   
24                                      CHEESE MONTEREY            14.5   
25                           CHEESE MOZZARELLA WHL MILK            17.0   
26                  CHEESE MOZZARELLA WHL MILK LO MOIST            16.1   
27                     CHEESE MOZZARELLA PART SKIM MILK            14.4   
28                 CHEESE MOZZARELLA LO MOIST PART-SKIM            26.8   
29                                      CHEESE MUENSTER            14.5   
...                                                 ...             ...   
8588         BABYFOOD CRL RICE W/ PEARS & APPL DRY INST            16.3   
8589                     BABYFOOD BANANA NO TAPIOCA STR             1.1   
8590                     BABYFOOD BANANA APPL DSSRT STR             0.6   
8591       SNACKS TORTILLA CHIPS LT (BAKED W/ LESS OIL)            15.7   
8592  CEREALS RTE POST HONEY BUNCHES OF OATS HONEY RSTD             7.3   
8593                         POPCORN MICROWAVE LOFAT&NA             8.6   
8594                       BABYFOOD FRUIT SUPREME DSSRT             0.4   
8595                               CHEESE SWISS LOW FAT            12.7   
8596             BREAKFAST BAR CORN FLAKE CRUST W/FRUIT            15.0   
8597                            CHEESE MOZZARELLA LO NA            15.7   
8598                           MAYONNAISE DRSNG NO CHOL             1.6   
8599                          OIL CORN PEANUT AND OLIVE             0.0   
8600                   SWEETENERS TABLETOP FRUCTOSE LIQ             0.5   
8601                              CHEESE FOOD IMITATION             2.9   
8602                                CELERY FLAKES DRIED            15.3   
8603           PUDDINGS CHOC FLAVOR LO CAL INST DRY MIX             3.9   
8604                    BABYFOOD GRAPE JUC NO SUGAR CND             NaN   
8605                   JELLIES RED SUGAR HOME PRESERVED             1.4   
8606                         PIE FILLINGS BLUEBERRY CND             0.4   
8607               COCKTAIL MIX NON-ALCOHOLIC CONCD FRZ             0.5   
8608            PUDDINGS CHOC FLAVOR LO CAL REG DRY MIX             5.1   
8609  PUDDINGS ALL FLAVORS XCPT CHOC LO CAL REG DRY MIX             0.9

In [ ]:
## --- pratique 13
# 1) Sélectionner et afficher seulement les colonnes qui utilisent comme unité de mesure les grammes 
#(c'est à dire qui se terminent par "(g)"). Pour cela:
#Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info 
#et convertir en liste utilisant la méthode tolist()

## 2) Créer une nouvelle liste qu'on nommera gram__columns, contenant seulement les colonnes se terminant 
##  par "(g)". Indice: la méthode endswith() retourne True si l'objet sur lequel on l'applique se termine
## par l'élément entre parenthèses. ex: total_(g).endswith("(g)") retourne True. Une boucle for est fortement conseillé pour parcourir tous les noms de colonne.

## 3) Sélectionner les colonnes de gram_columns pour le dataframe food_info et assigner le dataframe résultat 
## à la variable gram_df 

## 4) Afficher les 3 premières valeurs de ce dataframe gram_df



In [ ]:
##--- pratique 14
#Lire le dataset 'fandango_score_comparison' dans le dataframe fandango.
#Retourner un DataFrame contenant seulement la première et la dernière ligne et assigner le résultat à la variable first_last.
#Afficher le résultat.

###--- solution

fandango = pd.read_csv('fandango_score_comparison.csv')
first = 0
last = fandango.shape[0] - 1
first_last = fandango.iloc[[first,last]]
display(first_last)



FILM  RottenTomatoes  RottenTomatoes_User  \
0        Avengers: Age of Ultron (2015)              74                   86   
145  Kumiko, The Treasure Hunter (2015)              87                   63   

     Metacritic  Metacritic_User  IMDB  Fandango_Stars  Fandango_Ratingvalue  \
0            66              7.1   7.8             5.0                   4.5   
145          68              6.4   6.7             3.5                   3.5   

     RT_norm  RT_user_norm         ...           IMDB_norm  RT_norm_round  \
0       3.70          4.30         ...                3.90            3.5   
145     4.35          3.15         ...                3.35            4.5   

     RT_user_norm_round  Metacritic_norm_round  Metacritic_user_norm_round  \
0                   4.5                    3.5                         3.5   
145                 3.0                    3.5                         3.0   

     IMDB_norm_round  Metacritic_user_vote_count  IMDB_user_vote_count  \
0                4.0                        1330                271107   
145              3.5                          19                  5289   

     Fandango_votes  Fandango_Difference  
0             14846                  0.5  
145              41                  0.0  

[2 rows x 22 columns]

In [ ]:
##--- pratique 15
#Lire le fichier "fandango_score_comparison.csv" dans un dataframe qu'on nommera fandango.
#Afficher les 2 premières lignes de fandango.


fandango = pd.read_csv('fandango_score_comparison.csv')
fandango.head(2)

FILM  RottenTomatoes  RottenTomatoes_User  \
0  Avengers: Age of Ultron (2015)              74                   86   
1               Cinderella (2015)              85                   80   

   Metacritic  Metacritic_User  IMDB  Fandango_Stars  Fandango_Ratingvalue  \
0          66              7.1   7.8             5.0                   4.5   
1          67              7.5   7.1             5.0                   4.5   

   RT_norm  RT_user_norm         ...           IMDB_norm  RT_norm_round  \
0     3.70           4.3         ...                3.90            3.5   
1     4.25           4.0         ...                3.55            4.5   

   RT_user_norm_round  Metacritic_norm_round  Metacritic_user_norm_round  \
0                 4.5                    3.5                         3.5   
1                 4.0                    3.5                         4.0   

   IMDB_norm_round  Metacritic_user_vote_count  IMDB_user_vote_count  \
0              4.0                        1330                271107   
1              3.5                         249                 65709   

   Fandango_votes  Fandango_Difference  
0           14846                  0.5  
1           12640                  0.5  

[2 rows x 22 columns]